# -*- coding: utf-8 -*-
"""Day-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MsbOvce9q90KLgT4v4K2MUvdLJ2FqPcq

6)Write a program to find the smallest among three numbers.
"""

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))
if a <= b and a<= c:
    print("The smallest number is:", a)
elif b >= a and b<= c:
    print("The smallest number is:", b)
else:
    print("The smallest number is:", c)

"""

7)Write a program to Swap two numbers(Using Arithmetic operations)
"""

a=200
b=400
a=a+b
b=a-b
a=a-b
print(f"a:{a}")
print(f"b:{b}")

"""
8)Write a program to check whether a person is eligible to vote or not.
"""

age=int(input("Enter age: "))
if age>=18:
  print("Eligible to vote")
else:
  print("Not eligible to vote")

"""9)Write a program to check whether a given year is a leap year or not."""

year=int(input("Year: "))
if (year%4==0 and year%100!=0) or (year%400==0):
  print("Leap Year")
else:
  print("Not a Leap Year")

"""10)Write a program to check whether a number is positive, negative, or zero."""

num=int(input("Num: "))
if num>0:
  print("Positive Number")
elif num<0:
  print("Negative Number")
else:
  print("Zero")